imports:
    - { resource: parameters.yml }
    - { resource: parameters_app.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed!!!
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl
    locales: [pl]
    required_locales: [pl]
    upload_dir: '/uploads'
    portal.alias: 'dev'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        packages:
            app: ~
            admingenerator_css: ~
            admingenerator_js: ~
            admingenerator_custom_css: ~
            admingenerator_custom_js: ~
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - ParabolAdminCoreBundle:Form:field_type_help.html.twig
            - ParabolAdminCoreBundle:Form:field_type_blueimp_upload.html.twig
            - ParabolAdminCoreBundle:Form:field_type_google_location_map.html.twig
            # - ParabolAdminCoreBundle:Form:field_type_blueimp_upload.html.twig
    globals:
        metatag: @parabol.metatag
        portalAlias: %portal.alias%
        googleSiteVerification: %google.site_verification_filename%
        googleTrackingId: %google.tracking_id%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    assets:
        app: []
    use_controller: false
    bundles:        [ AdmingeneratorGeneratorBundle, ParabolAdminCoreBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs 
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"



# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }

admingenerator_generator:
    # choose  and enable at least one
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false

    dashboard_route: parabol_admin_core_dashboard
    # choose and uncomment only one
    base_admin_template: ParabolAdminCoreBundle::base_admin_uncompressed.html.twig
#    base_admin_template: AdmingeneratorGeneratorBundle::base_uncompressed.html.twig    
    # doctrine:
    #     class: Parabol\AdminCoreBundle\Generator\DoctrineGenerator
    templates_dirs: [ "%kernel.root_dir%/../src/Parabol/AdminCoreBundle/Resources/templates" ]
    logout_route: fos_user_security_logout
    twig:
        datetime_format: d M Y H:i:s
    form_types:
        doctrine_orm:
            # json_array: array
    #         datetime:     bootstrapdatetime

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Parabol\AdminCoreBundle\Entity\User    

simple_things_form_extra:
    help_extension: true

jms_security_extra:
    # Enables expression language
    expressions: true

jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    #strategy: prefix      

a2lix_translation_form:
    locales: %locales%
    required_locales: %required_locales%
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"    

liip_imagine:
    resolvers:
       default:
          web_path: 
             web_root: %kernel.root_dir%/../%web_dir%
             cache_prefix: cache
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../%web_dir%
    filter_sets:
        cache: ~
        admin_thumb:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [150, 150], mode: outbound }  
