app:
    resource: '@AppBundle/Controller/'
    type: annotation

parabol_admin_core_app:
    resource: "@ParabolAdminCoreBundle/Resources/config/routing/app.yml"

parabol_admin_core:
    resource: "@ParabolAdminCoreBundle/Resources/config/routing/admin.yml"
    prefix:   /admin
    options: { i18n: false }

