services:
    parabol.locales.subscriber:
        class: Parabol\LocaleBundle\EventListener\LocaleSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }